[project]
name = "evoked"
version = "0.2.0"
description = "A package for analyzing evoked local field potentials using template matching."
readme = "README.md"
authors = [{ name = "Blake Byer", email = "blake@blakebyer.com" }, ]

[tool.poetry]
packages = [{ include = "evoked", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
matplotlib = "3.10.8"
numpy = "2.4.1"
pandera = {extras = ["polars"], version = "^0.32.1"}
scipy = "1.17.0"
xlsxwriter = "^3.2.9"
openpyxl = "^3.1.5"
fastexcel = "^0.20.2"
polars = "^1.42.1"
neo = "^0.14.5"
polars-config-meta = {extras = ["polars"], version = "^0.3.4"}
mne-bids = "^0.19.0"
mne = "^1.12.1"
nicegui = "^3.15.0"
scikit-learn = "^1.9.0"
pytest = "^9.1.1"
pytest-cov = "^7.1.0"
dtaidistance = "^2.4.0"
ephyviewer = "^1.8.0"
pyside6 = "^6.11.2"

[project.scripts]
evoked-analysis = "evoked.analysis:main"
evoked-calibration = "evoked.calibration:main"
evoked-app = "evoked.app:main"

[project.urls]
repository = "https://github.com/blakebyer/evoked"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
